import os
from general_midi import *
from file_locations import *

program_mapping = {
  1: {
    DEFAULT_TRACK: ELECTRIC_PIANO_1,
    'me_item': TRUMPET,
    'me_lvup': TRUMPET,
  },
  2: {
    DEFAULT_TRACK: BASSOON,
    'me_item': PERCUSSIVE_ORGAN,
  },
  3: {
    DEFAULT_TRACK: VIBRAPHONE,
    'sys_steal': TRUMPET,
  },
  4: {
    DEFAULT_TRACK: ELECTRIC_PIANO_1,
    'sys_steal': TRUMPET,
  },
  5: {
    DEFAULT_TRACK: MARIMBA,
    'me_lankup': TIMPANI,
    'me_lvup': TIMPANI,
    'no_sound': ACOUSTIC_GRAND_PIANO,
  },
  6: MARIMBA,
  9: SYNTH_BASS_1,
  10: MUSIC_BOX,
  11: SYNTH_BASS_1,
  14: ELECTRIC_PIANO_1,
  15: PAD_1_NEW_AGE,
  16: PAD_1_NEW_AGE,
  18: CLARINET,
  20: {
    DEFAULT_TRACK: None,
    'me_wind_m': SEASHORE,
    'me_wind_s': SEASHORE,
  },
  21: SEASHORE,
  22: {
    DEFAULT_TRACK: GLOCKENSPIEL,
    'me_wave_s': SEASHORE,
  },
  23: {
    DEFAULT_TRACK: ACCORDION,
    'me_wave_m': SEASHORE,
  },
  25: SYNTH_BASS_1,
  28: ORCHESTRAL_HARP,
  30: VIBRAPHONE,
  31: {
    DEFAULT_TRACK: STRING_ENSEMBLE_1,
    'me_join': VIBRAPHONE,
  },
  32: STRING_ENSEMBLE_1,
  33: {
    DEFAULT_TRACK: SYNTH_STRINGS_1,
    'me_dunopen': VIBRAPHONE,
  },
  34: PERCUSSIVE_ORGAN,
  35: CHOIR_AAHS,
  38: ELECTRIC_PIANO_1,
  40: FLUTE,
  41: MARIMBA,
  42: {
    DEFAULT_TRACK: LEAD_1_SQUARE,
    'me_item': None,
  },
  43: PERCUSSIVE_ORGAN,
  44: PERCUSSIVE_ORGAN,
  45: PERCUSSIVE_ORGAN,
  47: {
    DEFAULT_TRACK: TUBA,
    'sys_steal': SYNTH_BASS_1
  },
  48: GLOCKENSPIEL,
  50: TROMBONE,
  51: TRUMPET,
  52: PERCUSSIVE_ORGAN,
  53: {
    DEFAULT_TRACK: TUBA,
    'me_evolution_e': ORCHESTRAL_HARP,
    'me_evolution': ORCHESTRAL_HARP,
    'me_exclude': ORCHESTRAL_HARP,
    'me_lankup': TROMBONE,
    'sys_steal': SYNTH_BASS_1,
  },
  54: PERCUSSIVE_ORGAN,
  55: FLUTE,
  56: {
    DEFAULT_TRACK: FLUTE,
    'me_exclude': VIBRAPHONE
  },
  57: VIBRAPHONE,
  59: TRUMPET,
  60: FRENCH_HORN,
  63: TROMBONE,
  64: TRUMPET,
  65: TRUMPET,
  66: TRUMPET,
  70: TRUMPET,
  74: CELESTA,
  75: PIZZICATO_STRINGS,
  77: VIOLIN,
  79: PIZZICATO_STRINGS,
  83: STEEL_DRUMS,
  85: STEEL_DRUMS,
  86: STEEL_DRUMS,
  88: PAN_FLUTE,
  90: MARIMBA,
  93: ELECTRIC_BASS_FINGER,
  94: SYNTH_STRINGS_1,
  96: LEAD_1_SQUARE,
  97: LEAD_2_SAWTOOTH,
  99: ELECTRIC_PIANO_1,
  100: CHOIR_AAHS,
  102: ACOUSTIC_GUITAR_NYLON,
  103: ELECTRIC_PIANO_1,
  104: ACOUSTIC_GRAND_PIANO,
  106: STRING_ENSEMBLE_1,
  107: LEAD_1_SQUARE,
  108: LEAD_1_SQUARE,
  113: ELECTRIC_BASS_FINGER,
  114: STRING_ENSEMBLE_1,
  118: STRING_ENSEMBLE_1,
  119: OBOE,
  120: ACOUSTIC_GUITAR_NYLON,
  121: TIMPANI,
  123: MARIMBA,
  124: MARIMBA,
}

program_transpose = {
  1: -12,
  3: {
    VIBRAPHONE: -12,
  },
  5: {
    TIMPANI: -12,
  },
  9: -24,
  15: -12,
  16: -12,
  25: -24,
  35: -12,
  48: 24,
  51: -12,
  53: {
    TROMBONE: 12,
  },
  55: -12,
  56: -12,
  63: -12,
  64: -12,
  66: -12,
  75: -12,
  85: -12,
  90: 12,
  93: -12,
  113: -12,
  121: -12,
}

percussion_parts = {
  24: ACOUSTIC_BASS_DRUM,
  25: SIDE_STICK,
  26: ACOUSTIC_SNARE,
  27: HAND_CLAP,
  28: ACOUSTIC_SNARE,
  29: LOW_TOM,
  30: CLOSED_HI_HAT,
  31: LOW_MID_TOM,
  33: None,
  34: OPEN_HI_HAT,
  35: HI_MID_TOM,
  36: None,
  38: RIDE_CYMBAL_1,
  39: MARACAS,
  40: PEDAL_HI_HAT,
  41: None,
  42: None,
  43: None,
  44: None,
  46: None,
  48: OPEN_HIGH_CONGA,
  49: LOW_BONGO,
  50: HIGH_BONGO,
  51: OPEN_HIGH_CONGA,
  52: LOW_CONGA,
  54: {
    DEFAULT_TRACK: TAMBOURINE,
    95: None,
  },
  57: MARACAS,
  58: VIBRASLAP,
  59: MARACAS,
  63: None,
  64: HIGH_WOODBLOCK,
  65: LOW_WOODBLOCK,
  68: MUTE_TRIANGLE,
  69: OPEN_TRIANGLE,
  72: {
    DEFAULT_TRACK: BELL_TREE,
    101: CLOSED_HI_HAT,
  },
  76: None,
  77: CRASH_CYMBAL_2,
  78: CRASH_CYMBAL_1,
  79: SPLASH_CYMBAL,
}

percussion_programs = {49, 87, 91, 92, 95, 101, 109, 117, 127}

source_midi_folder = os.path.join(sf2_folder, 'Pokémon Mystery Dungeon Blazing Light Stormy Adventure Squad')
